### ISSUE TITLE
bring it to the phone

### ISSUE THREAD

**Issue by ulrichard** [ZeroNerds/zeronet-snap#1]
On https://uappexplorer.com/app/zeronet.mkg20001  it is listed as amd64 only.
It would be great to use on the phone as well.

**Comment by mkg20001** [comment]
The problem: I use zerobundle, which is currently only available for 32/64 bit.
I will try to build the bundle in the snapcraft.yml

**Comment by mkg20001** [comment]
Sorry for the long delay, but I didn't had a device to test the arm version.
It should now work on armhf/arm64 (tested it with armhf)

As soon as snaps will be working on the phone, this should also work

**Comment by mkg20001** [comment]
Ubuntu Touch is dead. Closing this.
