### ISSUE TITLE
Won't Launch

### ISSUE THREAD

**Issue by ghost** [ZeroNerds/zeronet-snap#3]
Kubuntu 17.10 Beta

user@machine:~$snap run zeronet
- Please report snap specific errors (e.g. Read-only file system) to: https://github.com/mkg20001/zeronet-snap/issues
- and ZeroNet specific errors to: https://github.com/HelloZeroNet/ZeroNet/issues
Traceback (most recent call last):
  File "/snap/zeronet/484/launcher.py", line 145, in <module>
    main()
  File "/snap/zeronet/484/launcher.py", line 142, in main
    zero_start()
  File "/snap/zeronet/484/launcher.py", line 124, in zero_start
    zero_plugins()
  File "/snap/zeronet/484/launcher.py", line 87, in zero_plugins
    raise Exception("Path "+pld+" doest not exist")
Exception: Path /snap/zeronet/484/plugins/BigFile doest not exist

**Comment by ghost** [comment]
running `sudo snap run zeronet` results in everything working fine.

but then it shouldn't be running as root im guessing.

**Comment by mkg20001** [comment]
Have you run the previous version and then upgraded? I suspect the error occurred because the bigfile plugin got renamed. (BigFile => Bigfile)

**Comment by mkg20001** [comment]
Ok I fixed it now. New version should be available in less than 4 hours. Please tell me if it works without root after the update.

**Comment by ghost** [comment]
booted this morning. everything works as regular user.
