### ISSUE TITLE
Ubuntu 19.04 & zeronet snap version

### ISSUE THREAD

**Issue by katian** [ZeroNerds/zeronet-snap#9]
Hello,

on Ubuntu 19.04

`$ snap info zeronet`

say
```
channels:
  stable:    0.7.1-r4206 2019-09-07 (2061) 21MB -
  candidate: 0.7.1-r4206 2019-09-07 (2061) 21MB -
  beta:      0.7.1-r4206 2019-09-07 (2061) 21MB -
  edge:      0.7.1-r4206 2019-09-07 (2061) 21MB -
installed:   0.7.1-r4206            (2061) 21MB -

```

but when i run

`$ zeronet`

it say
` Version: 0.7.0 r4206, Python 3.6.8 (default, Jan 14 2019, 11:02:34)`

and

`$ snap list`

give me

`zeronet                  0.7.1-r4206                 2061      stable  mkg20001          -`

Thanks

**Comment by mkg20001** [comment]
Try `snap refresh --stable zeronet`

**Comment by mkg20001** [comment]
![screenshot](https://user-images.githubusercontent.com/7735145/64473954-7cfb5f80-d16d-11e9-883b-d5404e1f0721.png)

That's the culprit. The version was increased _after_ the revision which the update script incorrectly ignores.

Fixed builds should be out in up to 24 hours.

**Comment by katian** [comment]
Thank you mkg20001 !
:+1:
